[general]
version = "1.0.0"
log_level = "debug"

[notifications]
enabled = false

[[accounts]]
name = "lite"
emby_url = "https://lite.cn2gias.uk:443"
username = "jiabir"
password = "cjb123456"
api_key = ""
telegram_bot_token = "8518451828:AAEB4SVSLvpj2Uy0TKs9Bbq-V7I58d1CiOw"

[accounts.keepalive]
enabled = true
interval_hours = 6
min_minutes = 30
max_minutes = 120

[accounts.checkin]
telegram_bots = []
