[general]
version = "1.0.0"
log_level = "debug"

[notifications]
enabled = false

[[accounts]]
name = "test"
emby_url = "https://link00.okemby.org:8443"
username = "jabirc6"
password = "cjb123456"
api_key = ""
telegram_bot_token = "8518451828:AAEB4SVSLvpj2Uy0TKs9Bbq-V7I58d1CiOw"

[accounts.keepalive]
enabled = false

[accounts.checkin]
telegram_bots = ["fortesttlbot"]
